{"timestamp":"2025-08-31T18:55:12.275121","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-31T18:55:12.275610","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/parse_habr_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-31T18:55:13.522054","level":"warning","event":"Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f6a4f70bc50>: Failed to resolve 'clickhouse' ([Errno -2] Name or service not known)\")': /?","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-31T18:55:13.612159","level":"warning","event":"Unexpected Http Driver Exception","logger":"clickhouse_connect.driver.httpclient"}
{"timestamp":"2025-08-31T18:55:13.612664","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"Error HTTPConnectionPool(host='clickhouse', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f6a4f709e50>: Failed to resolve 'clickhouse' ([Errno -2] Name or service not known)\")) executing HTTP request attempt 1 (http://clickhouse:8123)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/parse_habr_dag.py","lineno":35,"name":"save_feeds"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pipeline_tools/db.py","lineno":49,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/__init__.py","lineno":122,"name":"create_client"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py","lineno":165,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py","lineno":70,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py","lineno":75,"name":"_init_common_settings"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py","lineno":368,"name":"command"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py","lineno":468,"name":"_raw_request"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='clickhouse', port=8123): Max retries exceeded with url: /? (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f6a4f709e50>: Failed to resolve 'clickhouse' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py","lineno":456,"name":"_raw_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":143,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":278,"name":"request_encode_body"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py","lineno":459,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7f6a4f709e50>: Failed to resolve 'clickhouse' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
